#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "pairdrop"
name = "PairDrop"
description.en = "Local file sharing in your browser"
description.fr = "Partage de fichiers locaux dans votre navigateur"

version = "1.11.2~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0-only"
website = "https://pairdrop.net/"
demo = "https://pairdrop.net/"
admindoc = "https://github.com/babstar99/PairDrop/blob/master/docs/host-your-own.md"
code = "https://github.com/schlagmichdoch/PairDrop"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/schlagmichdoch/PairDrop/archive/refs/tags/v1.11.2.tar.gz"
        sha256 = "8773944d01cbb8f2ab2ab1c47f1ac3b58f16a5ddf29d702f2fb4a535f4663b06"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
